config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  scope module: 'welcome' do
    get :sunburst
    get :viva
    get :tree
  end

  resources :api, only: [] do
    collection do
      get :level1
      get :level3
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  def level1
    render json: { status: 'success', data: Troux.new.level1 }
  end

  def level3
    render json: { status: 'success', data: Troux.new.level3 }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def sunburst
  end

  def viva
  end

  def tree
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrouxVisualizations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<style type="text/css">
  .desc {
    height: 120px;
  }
  .img-circle{
    background-color: #eee;
    opacity: 0.7;
  }
</style>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <h3 style='margin:5px'>Troux Visualizations</h3>
      </a>
    </div>
  </div>
</div>

<br><br>
<br><br>

<div class='container'>
  <div class="row">
    <div class="col-md-4" style='text-align:center;'>
      <%= image_tag 'sunburst.png', class: 'img-circle', size: '140x140' %>
      <h3><%= link_to 'Zoomable Sunburst', sunburst_path %></h3>
      <p class='desc' style='text-align:left;'>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
      <p><%= link_to 'View details »', sunburst_path, class: 'btn btn-default' %>
    </div>

    <div class="col-md-4" style='text-align:center;'>
      <%= image_tag 'viva_logo.png', class: 'img-circle', size: '140x140' %>
      <h3><%= link_to 'VivaGraph', viva_path %></h3>
      <p  class='desc' style='text-align:left;'>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
      <p><%= link_to 'View details »', viva_path, class: 'btn btn-default' %></p>
    </div>

    <div class="col-md-4" style='text-align:center;'>
      <%= image_tag 'tree_logo.png', class: 'img-circle', size: '140x140' %>
      <h3><%= link_to 'Zoomable & Collapsible Tree', tree_path %></h3>
      <p class='desc' style='text-align:left;'>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><%= link_to 'View details »', tree_path, class: 'btn btn-default' %></p>
    </div>
  </div>
</div>

<div style="position: fixed;right: 100px;bottom:0px;">
  © PricewaterhouseCoopers LLP 2014
</div>

app/views/welcome/sunburst.html.erb
<style type="text/css">
  path {
    stroke: #fff;
    fill-rule: evenodd;
  }
</style>

<script>
  amplify.request('level1', {}, function(result) {
    console.log(result);

    var width = 960,
        height = 700,
        radius = Math.min(width, height) / 2;

    var x = d3.scale.linear()
        .range([0, 2 * Math.PI]);

    var y = d3.scale.sqrt()
        .range([0, radius]);

    var color = d3.scale.category20c();

    var svg = d3.select("body").append("svg")
        .attr("width", width)
        .attr("height", height+100)
      .append("g")
        .attr("transform", "translate(" + width / 2 + "," + (height / 2 + 50) + ")");

    var tip = d3.tip().attr('class', 'd3-tip').html(function(d) { return d.name; });

    /* Invoke the tip in the context of your visualization */
    svg.call(tip);

    var getChildren = function(parent_id) {
      if(parent_id == 'root'){
        return getRoots();
      }
      else
        return _.select(result["elem"], 
          function(e) {
            return e["parentCapability"].length>0 && e["parentCapability"][0]["_id"] == parent_id;
          });
    };

    var getRoots = function() {
      return  _.select(result["elem"],
          function(e) {
            return e["parentCapability"].length == 0;
          });
    };

    var root_node = { _id: 'root', name: 'Capabilities' };

    var partition = d3.layout.partition()
        .value(function(d) { return 1; })
        .children(function(d) { return getChildren(d["_id"]); })

    var arc = d3.svg.arc()
        .startAngle(function(d) { return Math.max(0, Math.min(2 * Math.PI, x(d.x))); })
        .endAngle(function(d) { return Math.max(0, Math.min(2 * Math.PI, x(d.x + d.dx))); })
        .innerRadius(function(d) { return Math.max(0, y(d.y)); })
        .outerRadius(function(d) { return Math.max(0, y(d.y + d.dy)); });

    var path = svg.selectAll("path")
        .data(partition.nodes(root_node))
      .enter().append("path")
        .attr("d", arc)
        .text('12')
        .style("fill", function(d) { return color((d.children ? d : d.parent).name); })
        .on("mouseover", tip.show)
        .on("mouseout", tip.hide)
        .on("click", click);

    function click(d) {
      path.transition()
        .duration(750)
        .attrTween("d", arcTween(d));
    }

    d3.select(self.frameElement).style("height", height + "px");

    // Interpolate the scales!
    function arcTween(d) {
      var xd = d3.interpolate(x.domain(), [d.x, d.x + d.dx]),
          yd = d3.interpolate(y.domain(), [d.y, 1]),
          yr = d3.interpolate(y.range(), [d.y ? 20 : 0, radius]);
      return function(d, i) {
        return i
            ? function(t) { return arc(d); }
            : function(t) { x.domain(xd(t)); y.domain(yd(t)).range(yr(t)); return arc(d); };
      };
    }
  })
</script>

app/views/welcome/viva.html.erb
<style type="text/css">
  circle {
    cursor: pointer;
  }

  #viva-container svg {
    overflow: visible;
  }
</style>
<div id="viva-container" style="width: 100%; height: 100%; min-height: 800px;"></div>
<script>
amplify.request('level1', {}, function(data_a) {
  console.log(data_a);

  var level1Data;
  var graph
  var getChildren = function(parent_id) {
    data_a = data_a || level1Data;
    if (parent_id == 'root') {
      return getRoots();
    } else
      return _.select(data_a["elem"],
        function(e) {
          return e["parentCapability"].length > 0 && e["parentCapability"][0]["_id"] == parent_id;
        });
  };

  var getRoots = function(data_a) {
    return _.select(data_a["elem"],
      function(e) {
        return e["parentCapability"].length == 0;
      });
  };


  function main() {

    graph = Viva.Graph.graph();
    graph.addNode('Capabilities', {
      name: 'Capabilities'
    });

    var graphics = Viva.Graph.View.svgGraphics();
    var layout = Viva.Graph.Layout.forceDirected(graph, {
      springLength: 200,
      springCoeff: 0.0001,
      dragCoeff: 0.01,
      gravity: -20,
      theta: 0.5
    });

    // $.getJSON("sample_data/a.json", function(json) {
    //     level1Data = json;
    var roots = getRoots(data_a);
    var add1stNodes = function() {
      roots.forEach(function(data) {
        data.level = 1;
        graph.addNode(data.name, data);
        graph.addLink('Capabilities', data.name, data);
      });
    };

    add1stNodes();


    // });

    var nodeSize = 24;


    graphics.node(function(node) {
      // This time it's a group of elements: http://www.w3.org/TR/SVG/struct.html#Groups
      var ui = Viva.Graph.svg('g'),
        // Create SVG text element with user id as content
        svgText = Viva.Graph.svg('text').text(node.id),
        node_title_shadow = Viva.Graph.svg('text').attr('y', '5px').text(node.id).attr('stroke', '#adadad').attr('stroke-width', '1px').attr('stroke-opacity', '0.8').attr('font-size', '12px').attr('font-family', 'Arial').attr('text-anchor', 'right'),
        circle = Viva.Graph.svg('circle').attr('stroke', '#606060').attr('stroke-width', '1.5px');

      if (node.id == 'Capabilities') {
        node_title_shadow.attr('x', '30px')
        svgText.attr('y', '-44px');
        circle.attr('r', '25px').attr("fill", '#F9906F');
      } else if (node.data.level == 1) {
        node_title_shadow.attr('x', '25px')
        svgText.attr('y', '-34px');
        circle.attr('r', '20px').attr("fill", '#E0EEE8');
      } else if (node.data.level == 2) {
        node_title_shadow.attr('x', '25px').attr('font-size', '12px')
        svgText.attr('y', '-24px');
        circle.attr('r', '15px').attr("fill", '#7FECAD');
      } else {
        node_title_shadow.attr('x', '25px').attr('font-size', '12px')
        svgText.attr('y', '-14px');
        circle.attr('r', '10px').attr("fill", '#EEDEB0');
      }

      ui.append(node_title_shadow);
      // ui.append(svgText);
      ui.append(circle);
      $(ui).click(function() { // click action

        if (graph.getLinks(node.id).length == 1) {
          console.log('add link');
          if (node.data.childCapabilities) {
            node.data.childCapabilities.forEach(function(child) {
              child.level = 2;
              graph.addNode(child.name, child)
              graph.addLink(node.id, child.name, child);
            })
          } else {
            var childs = getChildren(node.data._id);
            childs.forEach(function(child) {
              child.level = 3;
              graph.addNode(child.name, child);
              graph.addLink(node.id, child.name, child);
            })
          }
        } else if (node.id == 'Capabilities' && graph.getLinks(node.id).length == 0) {
          add1stNodes();
        } else {


          var tarNodes = [];
          var tarLinks = [];
          var _queryRelatedItems = function(_nodeId) {
            var links = graph.getLinks(_nodeId);
            links.forEach(function(link) {
              if (link.fromId == _nodeId) {
                tarNodes.push(link.toId);
                tarLinks.push(link);
                _queryRelatedItems(link.toId);
              }
            });
          };
          _queryRelatedItems(node.id);
          tarNodes.forEach(function(tn) {
            graph.removeNode(tn);
          });
          tarLinks.forEach(function(tl) {
            graph.removeLink(tl);
          });
        }

      });

      return ui;
    }).placeNode(function(nodeUI, pos) {

      nodeUI.attr('transform',
        'translate(' +
        (pos.x) + ',' + (pos.y) +
        ')');
    });

    graphics.link(function(link) {
      var path = Viva.Graph.svg('path');
      path.attr('stroke', '#333');
      return path;


    }).placeLink(function(linkUI, fromPos, toPos) {
      // linkUI - is the object returend from link() callback above.
      var data = 'M' + fromPos.x + ',' + fromPos.y +
        'L' + toPos.x + ',' + toPos.y;

      // 'Path data' (http://www.w3.org/TR/SVG/paths.html#DAttribute )
      // is a common way of rendering paths in SVG:
      linkUI.attr("d", data);
    });

    var renderer = Viva.Graph.View.renderer(graph, {
      graphics: graphics,
      layout: layout,
      container : $('#viva-container')[0]
    });
    renderer.run();
  }

    main();
});
</script>